### ISSUE TITLE
dataset_url has been changed in radar_robotcar_dataset_scraper.py

### ISSUE THREAD

**Issue by mrgransky** [oxford-robotics-institute/radar-robotcar-dataset-sdk#6]
The previous `dataset_url` seems to be broken in the following line of `radar_robotcar_dataset_scraper.py`:

`flags.DEFINE_string("dataset_url", "http://ori.ox.ac.uk/datasets/radar-robotcar-dataset","Oxford Radar RobotCar Dataset url")`

One can replace it with a new link as follows:

`flags.DEFINE_string("dataset_url", "https://oxford-robotics-institute.github.io/radar-robotcar-dataset","Oxford Radar RobotCar Dataset url")`

**Comment by dbarnes** [comment]
Thanks for spotting this @mrgransky! 

The Oxford Robotics Institute website was recently migrated to a new system and it seems some redirects we accidentally dropped. We want to keep the previous `dataset_url` and restore the redirects so that the url in the publication stays valid but you're absolutely right with your fix for the time being.

I am no longer a student at ORI but perhaps @mttgdd / @oxford-robotics-institute can help give an eta on this?

**Comment by mttgdd** [comment]
Hi, @dbarnes is correct concerning the broken redirect. Nevertheless, I have just changed the default flag value to the ultimate destination for that redirect (see 301f75cee6a28df1fa8165b92467f30a040d637c), so this should work now. I am going to close the issue, but please feel free to reopen it if there is still a problem with the scraper.
